backend_url: "http://192.168.1.5:5000/upload"  #The url where the POST request is sent
detection_threshold: 10                        #Threshold above which the system assumes there might have been an accident
delay_after_detection_ms: 1000                 #Delay between detections, to suppress multiple entries. This is also the duration of the sound of the buzzer
usb_cam_id: "/dev/video0"                      #Name of usb device-used only if use_usb==1
